ogive_user:
    resource: "@OGIVEUserBundle/Resources/config/routing.yml"
    prefix:   /user

ogive_project:
    resource: "@OGIVEProjectBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
ogive_project_default:    
    resource: "@OGIVEProjectBundle/Controller/DefaultController.php"
    type:     rest
    
ogive_project_project:    
    resource: "@OGIVEProjectBundle/Controller/ProjectController.php"
    type:     rest
        
ogive_project_decompte:    
    resource: "@OGIVEProjectBundle/Controller/DecompteController.php"
    type:     rest
    
ogive_project_task:    
    resource: "@OGIVEProjectBundle/Controller/TaskController.php"
    type:     rest
    
ogive_project_project_manager:    
    resource: "@OGIVEProjectBundle/Controller/ProjectManagerController.php"
    type:     rest
    
ogive_project_holder:    
    resource: "@OGIVEProjectBundle/Controller/HolderController.php"
    type:     rest
    
ogive_project_service_provider:    
    resource: "@OGIVEProjectBundle/Controller/ServiceProviderController.php"
    type:     rest
    
ogive_project_other_contributor:    
    resource: "@OGIVEProjectBundle/Controller/OtherContributorController.php"
    type:     rest
    
ogive_project_planning:    
    resource: "@OGIVEProjectBundle/Controller/PlanningController.php"
    type:     rest
    
ogive_project_user:    
    resource: "@OGIVEUserBundle/Controller/UserController.php"
    type:     rest