ogive_user:
    resource: "@OGIVEUserBundle/Resources/config/routing.yml"
    prefix:   /user

ogive_project:
    resource: "@OGIVEProjectBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
ogive_project_project:    
    resource: "@OGIVEProjectBundle/Controller/ProjectController.php"
    type:     rest
        
ogive_project_decompte:    
    resource: "@OGIVEProjectBundle/Controller/DecompteController.php"
    type:     rest
    
ogive_project_task:    
    resource: "@OGIVEProjectBundle/Controller/TaskController.php"
    type:     rest