<?php

namespace OGIVE\ProjectBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * DecompteTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecompteTaskRepository extends EntityRepository
{
    public function deleteDecompteTask(\OGIVE\ProjectBundle\Entity\DecompteTask $decompteTask) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $subDecompteTasks = $decompteTask->getSubDecompteTasks();
            foreach ($subDecompteTasks as $subDecompteTask) {
                $this->deleteDecompteTask($subDecompteTask);
            }
            $em->remove($decompteTask);
            $em->flush();
            $em->getConnection()->commit();
            return true;
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveDecompteTask(\OGIVE\ProjectBundle\Entity\DecompteTask $decompteTask) {
        $em= $this->_em;
        $decompteTask->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($decompteTask);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $decompteTask;
    }

    public function updateDecompteTask(\OGIVE\ProjectBundle\Entity\DecompteTask $decompteTask) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($decompteTask);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $decompteTask;
    }
    public function getAll($offset = null, $limit = null, $search_query = null, $decompte = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = 1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.taskName)', ':search_query'), $qb->expr()->like('lower(e.taskNumber)', ':search_query'), $qb->expr()->like('lower(e.searchData)', ':search_query')
            ));
            $search_query = strtolower($search_query);
            $qb->setParameter('search_query', '%' . strtolower($search_query) . '%');
        }
        
        if ($decompte && $decompte != "0") {
            $qb->join("e.decompte", 'u');
            $qb->andWhere('u.id = :decompte');
            $qb->setParameter("decompte", intval($decompte));
        }
        $qb->orderBy('e.createDate', 'DESC');
        
        if ($offset) {
            $qb->setFirstResult($offset);
        }
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }
    
    public function getDecompteTaskByDecompteAndTask($task = null, $decompte = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = 1');
        
        if ($task && $task != "0") {
            $qb->join("e.task", 't');
            $qb->andWhere('t.id = :task');
            $qb->setParameter("task", intval($task));
        }
        
        if ($decompte && $decompte != "0") {
            $qb->join("e.myDecompte", 'u');
            $qb->andWhere('u.id = :myDecompte');
            $qb->setParameter("myDecompte", intval($decompte));
        }
        try{
            return $qb->getQuery()->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $ex) {
            return null;
        }
        
    }
    
    
    
    
    public function getDecompteTaskQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->andWhere('e.state = :state')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
}
